### ISSUE TITLE
arstarst

### ISSUE THREAD

**Issue by clux** [clux/testrepo#3]
### Current and expected behavior

arstarstarst

### Possible solution

arstarstarstar

### Additional context

wfpqwfpwfpwfp

### Environment

1.20

### Configuration and features

```toml
kube = { version = "0.63.1", features = ["runtime"] }
k8s-openapi = { version = "0.13.0", features = ["v1_21"], default-features = false }
```

### Affected crates

kube-core, kube-derive

### Would you like to work on this feature?

yes
